### ISSUE TITLE
[Feature request] Banned words

### ISSUE THREAD

**Issue by Qwerty-Space** [RememberTheAir/GroupButler#257] opened 2017-12-14 17:53 UTC
Should be self explanatory.  The user selects "banned words" in antispam, and can add words to the list with a command, or something.  If a user says these words in a message then they're handled the same as other spam.

**Comment by RememberTheAir** [comment] 2017-12-15 14:26
Duplicate of #232 :)

**Closed by RememberTheAir** 2017-12-15 14:26 UTC
