### ISSUE TITLE
 [CURL-EASY][URL_MALFORMAT] URL using bad/illegal format or missing URL (3)

### ISSUE THREAD

**Issue by codingsett** [RememberTheAir/GroupButler#274] opened 2018-02-14 00:44 UTC
I followed the exact procedures and this what i get when  i try to run the bot

` [CURL-EASY][URL_MALFORMAT] URL using bad/illegal format or missing URL (3)`

why does this happen and what is the fix to this

**Comment by NotAFile** [comment] 2018-02-14 02:04
I guess this is related to something in your configuration being invalid? It doesn't happen for anyone else, either way.

**Comment by RememberTheAir** [comment] 2018-02-14 15:39
Duplicate of #229 - there's a solution there

**Closed by RememberTheAir** 2018-02-14 15:39 UTC
