### ISSUE TITLE
[Bug] Error caused the bot to restart

### ISSUE THREAD

**Issue by Qwerty-Space** [RememberTheAir/GroupButler#297] opened 2018-04-30 16:04 UTC
### Steps to reproduce
Unknown.

### Expected behaviour
Normal function

### Actual behaviour
The bot gets stuck in a  bit of a loop, and crashes

```
lua: ./lua/methods.lua:40: Expected value but found invalid token at character 1
groupbutler_1  | stack traceback:
groupbutler_1  |        [C]: in function 'decode'
groupbutler_1  |        ./lua/methods.lua:40: in function <./lua/methods.lua:38>
groupbutler_1  |        (...tail calls...)
groupbutler_1  |        polling.lua:39: in main chunk
groupbutler_1  |        [C]: in ?
```

This repeats several times, then the bot restarts.  This has happened on multiple occasions.

**Operating system:** 
Debian.  Master branch using Docker.

**Comment by Obey138** [comment] 2018-04-30 17:01
This is what happens when the program can't connect to Bot API

**Comment by NotAFile** [comment] 2018-04-30 17:08
duplicate of #281

**Closed by NotAFile** 2018-04-30 17:08 UTC
